version: '3.8'

# services - here i am going to list containers that i want to build
# each service, actually describes a docker run command
services:
  database:
    container_name: meetings-db-compose
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=meetings_management_orriez
      - MYSQL_USER=orriez
      - MYSQL_PASSWORD=1234
      - MYSQL_TCP_PORT=3306
    ports:
      - "3310:3306"
    build: ./database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  backend:
    container_name: meetings-backend-compose
    environment:
      - NODE_ENV=compose
    ports:
      - "3021:3000"
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
        
  frontend:
    container_name: meetings-frontend-compose
    ports:
      - 3015:80
    build:
      context: ./frontend
      dockerfile: Dockerfile.compose

